# pylint: disable=invalid-name
"""django import"""
# Generated by Django 4.1.2 on 2022-10-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    """book cover migration"""

    dependencies = [
        ("books", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, upload_to="covers/"),
        ),
    ]
