# Generated by Django 4.1.2 on 2022-10-20 23:54

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='images',
            field=models.ImageField(blank=True, upload_to=books.models.get_image_path),
        ),
    ]
