# Generated by Django 4.1.2 on 2022-10-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
